/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package MQTT;
import com.hivemq.client.mqtt.mqtt5.*;
import com.hivemq.client.mqtt.mqtt5.message.publish.*;
import java.util.function.Consumer;
import java.nio.charset.StandardCharsets;


public class Mqtt {

    private String host; // use your host-name, it should look like '<alphanumeric>.s2.eu.hivemq.cloud'
    private String password;
    private Mqtt5BlockingClient client;
    
    public Mqtt(String id,String host){
       this.host=host;
        client = Mqtt5Client.builder()
       .identifier(id) // use a unique identifier
       .serverHost(host)
       .buildBlocking();
        client.connect();
        System.out.println("connect");

    }
    public void suscribe(String topic, Consumer<Mqtt5Publish> callback){
        client.toAsync().subscribeWith()
                .topicFilter(topic)
                .callback(callback)
                .send();
        System.out.println("suscribe");

    }

    public void publish(String topic, String msg){
        client.publishWith()
            .topic(topic)
            .payload(msg.getBytes(StandardCharsets.UTF_8))
            .send();
    }
}
