INSERT INTO public."ControllableDevice" values (nextval('seq_controllable'),'GroovEpic', 'GRV-EPIC-PR2');
INSERT INTO public."ControllableDevice" values (nextval('seq_controllable'),'RIO', 'opto22');
INSERT INTO public."ControllableDevice" values (nextval('seq_controllable'),'PlantaPiloto', 'bio');

INSERT INTO public."IOModule" values (nextval('seq_IOModule'),'name','GRV-OAC-12',1);
INSERT INTO public."IOModule" values (nextval('seq_IOModule'),'name','GRV-IACI-12 ',1);
INSERT INTO public."IOModule" values (nextval('seq_IOModule'),'T20','Tanque 20 litros',3);

INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','COUNTER','temperature',3,'ANTIESPUMANTE.ACC');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_AGITADOR');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_FCV101');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P101');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P102');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P103');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P104_CHILLER');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_ACIDO_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_BASE_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_GAS');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_SUSTRATO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_10');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_30');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_100');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_10');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_30');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_100');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PH_MAXIMO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PH_MINIMO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.SP');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KP');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KD');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'RANGO_CALENTAMIENTO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'RANGO_ENFRIAMIENTO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_FLUJO_GAS');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_NIVEL');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_NIVEL1');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_OXIGENO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_PH');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_PRESION');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE101');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE102');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE103');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE106');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV101');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV102');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV103');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV104');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV105');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_DOSIFICACION');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_ESPERA_DOSIFICACION');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_SANITIZACION_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TEMP_TE106');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TEMPE_TE101');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_CALENTAMIENTO_CICLO_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_CALENTAMIENTO_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TIEMPO_ELECTRO');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_ENFRIAMIENTO_CICLO_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_ENFRIAMIENTO_HMI');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TIEMPO_FINAL_SANITIZACION');
INSERT INTO public."Channel" values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'VAPOR_TEMPE_TE101');
