INSERT INTO icesi_bionic_plantapiloto.ControllableDevice values (nextval('seq_controllable'),'GroovEpic', 'GRV-EPIC-PR2');
INSERT INTO icesi_bionic_plantapiloto.ControllableDevice values (nextval('seq_controllable'),'RIO', 'opto22');
INSERT INTO icesi_bionic_plantapiloto.ControllableDevice values (nextval('seq_controllable'),'PlantaPiloto', 'bio');

INSERT INTO icesi_bionic_plantapiloto.IOModule values (nextval('seq_IOModule'),'name','GRV-OAC-12',1);
INSERT INTO icesi_bionic_plantapiloto.IOModule values (nextval('seq_IOModule'),'name','GRV-IACI-12 ',1);
INSERT INTO icesi_bionic_plantapiloto.IOModule values (nextval('seq_IOModule'),'T20','Tanque 20 litros',3);
INSERT INTO icesi_bionic_plantapiloto.IOModule values (nextval('seq_IOModule'),'40B','Tanque 20 litros',3);

INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','COUNTER','temperature',3,'ANTIESPUMANTE.ACC');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_AGITADOR');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_FCV101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'ENT_P104_CHILLER');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_ACIDO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_BASE_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_GAS');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'FLUJO_SUSTRATO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_10');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_30');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_ACIDO_100');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_10');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_30');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PENDIENTE_BASE_100');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PH_MAXIMO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PH_MINIMO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.SP');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KP');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'PID_PRESION.KD');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'RANGO_CALENTAMIENTO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'RANGO_ENFRIAMIENTO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_FLUJO_GAS');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_NIVEL');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_NIVEL1');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_OXIGENO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_PH');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_PRESION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'SAL_RTD_TE106');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV104');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',3,'SV105');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_DOSIFICACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_ESPERA_DOSIFICACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'T_SANITIZACION_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TEMP_TE106');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TEMPE_TE101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_CALENTAMIENTO_CICLO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_CALENTAMIENTO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TIEMPO_ELECTRO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_ENFRIAMIENTO_CICLO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',3,'TIEMPO_ENFRIAMIENTO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'TIEMPO_FINAL_SANITIZACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',3,'VAPOR_TEMPE_TE101');


INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','COUNTER','temperature',4,'ANTIESPUMANTE.ACC');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_AGITADOR');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_FCV101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_P101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_P102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_P103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'ENT_P104_CHILLER');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'FLUJO_ACIDO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'FLUJO_BASE_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'FLUJO_GAS');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'FLUJO_SUSTRATO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_ACIDO_10');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_ACIDO_30');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_ACIDO_100');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_BASE_10');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_BASE_30');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PENDIENTE_BASE_100');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PH_MAXIMO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PH_MINIMO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PID_PRESION.SP');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PID_PRESION.KP');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PID_PRESION.KI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'PID_PRESION.KD');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'RANGO_CALENTAMIENTO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'RANGO_ENFRIAMIENTO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_FLUJO_GAS');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_NIVEL');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_NIVEL1');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_OXIGENO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_PH');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_PRESION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_RTD_TE101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_RTD_TE102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_RTD_TE103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_RTD_TE106');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',4,'SV101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',4,'SV102');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',4,'SV103');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',4,'SV104');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','BOOL','temperature',4,'SV105');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'T_DOSIFICACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'T_ESPERA_DOSIFICACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'T_SANITIZACION_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'TEMP_TE106');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'TEMPE_TE101');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',4,'TIEMPO_CALENTAMIENTO_CICLO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',4,'TIEMPO_CALENTAMIENTO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'TIEMPO_ELECTRO');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',4,'TIEMPO_ENFRIAMIENTO_CICLO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','DINT','temperature',4,'TIEMPO_ENFRIAMIENTO_HMI');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'TIEMPO_FINAL_SANITIZACION');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'VAPOR_TEMPE_TE101');

INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_O2');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'SAL_CO2');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'Q_O2');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'Q_CO2');
INSERT INTO icesi_bionic_plantapiloto.Channel values (nextval('seq_Channel'),'range','signal','REAL','temperature',4,'RQ');

